object Versions {
    const val gradle = "7.1.0"
    const val kotlinGradle = "1.6.10"
    const val androidXCore = "1.7.0"
    const val appCompat = "1.4.1"
    const val material = "1.5.0"
    const val constraintLayout = "2.1.3"
    const val androidXLegacySupport = "1.0.0"
    const val lifecycle = "2.4.0"
    const val arch = "2.1.0"
    const val room = "2.4.1"
    const val navigation = "2.3.5"
    const val coroutines = "1.6.0"
    const val dagger = "2.40.5"
    const val retrofit = "2.9.0"
    const val httpLoggingInterceptor = "4.9.3"
    const val glide = "4.12.0"
    const val truth = "1.1.3"
    const val robolectric = "4.7.3"
    const val mockito = "2.21.0"
    const val mockitoInline = "2.13.0"
    const val jUnit = "4.13.2"
    const val jUnitExt = "1.1.3"
    const val espresso = "3.4.0"
    const val mockWebServer = "4.9.3"
}
